### ISSUE TITLE
E5113: Error while calling lua chunk: Vim:E6100: "log" is not a valid stdpath

### ISSUE THREAD

**Issue by SuCicada** [Hwloser/hwloser-vim#1]
I use the install.sh to install.  Then I tap `nvim` in console.
Then I meet the error follow:

OS: Linux vultr 5.15.0-60-generic #66-Ubuntu SMP Fri Jan 20 14:29:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

```
Error detected while processing /root/.hwloser-vim/init.lua:
E5113: Error while calling lua chunk: Vim:E6100: "log" is not a valid stdpath
stack traceback:
        [C]: in function 'stdp'
        ....config/nvim/lua/standardpath/standardpathdefination.lua:126: in main chunk
        [C]: in function 'require'
        /root/.config/nvim/lua/standardpath/init.lua:15: in main chunk
        [C]: in function 'require'
        /root/.config/nvim/lua/bootstrap.lua:11: in main chunk
        [C]: in function 'require'
        /root/.config/nvim/init.lua:4: in main chunk
Press ENTER or type command to continue
```

plz help me

**Comment by huanwei1208** [comment]
# Description

I know, your neovim is not the nightly neovim, whcih is latest version of neovim.

My Macos「command - :version」: 

NVIM v0.9.0-dev-988+gf905ab045-dirty
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by huanwei@huanweideMacBook-Pro.local

# How fix it

Macos: brew install --HEAD neovim
Ubuntu: 
1. sudo apt-get install python-software-properties
2. sudo add-apt-repository ppa:neovim-ppa/stable
3. sudo apt-get update
4. sudo apt-get install python-dev python-pip python3-dev python3-pip
5. sudo apt-get install neovim

**Comment by SuCicada** [comment]
before I run these commands:
>nvim --version
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3

after I update:

>nvim --version
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by team+vim@tracker.debian.org



but still error

**Comment by huanwei1208** [comment]
> before I run these commands:
> 
> > nvim --version
> > NVIM v0.6.1
> > Build type: Release
> > LuaJIT 2.1.0-beta3
> 
> after I update:
> 
> > nvim --version
> > NVIM v0.7.2
> > Build type: Release
> > LuaJIT 2.1.0-beta3
> > Compiled by [team+vim@tracker.debian.org](mailto:team+vim@tracker.debian.org)
> 
> but still error

i`ll try fix it. Try it again after git pull new codes.

**Comment by SuCicada** [comment]
<img width="975" alt="image" src="https://user-images.githubusercontent.com/33519267/222057901-22d8333e-22b6-44e2-9500-b0f3b72967aa.png">

**Comment by huanwei1208** [comment]
> <img alt="image" width="975" src="https://user-images.githubusercontent.com/33519267/222057901-22d8333e-22b6-44e2-9500-b0f3b72967aa.png">

It`s look like a nother problems of lower version。

1. i will hidden it by check if we could set it, but we cloud enjoy the feature of bufferline, which could hover close button.
2. you can install from source code/ from https://github.com/neovim/neovim.git

## install command
4. git clone https://github.com/neovim/neovim.git && cd neovim
5. git checkout nightly -b nightly
6. make CMAKE_BUILD_TYPE=RelWithDebInfo && sudo make install

**Comment by SuCicada** [comment]
>Error detected while processing /root/.hwloser-vim/init.lua:
lazy.nvim requires Neovim >= 0.8.0
Press ENTER or type command to continue

**Comment by SuCicada** [comment]
I know what should i do. Thanks.
